# Generated by Django 3.2.9 on 2022-11-06 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('identity', models.IntegerField(blank=True, choices=[(0, '顧客'), (1, '廠商')], default=True)),
                ('username', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('gender', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], default=1, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('tax_ID_number', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('tax_ID_number', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HandSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('thumb_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('index_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('index_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('middle_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('middle_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ring_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ring_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('little_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('little_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('palm_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('palm_width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hand_size', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
