# Generated by Django 3.2.9 on 2022-11-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_size', models.CharField(max_length=10)),
                ('centimeter', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('material_color', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('threeD_model', models.FileField(blank=True, null=True, upload_to='gltf/')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='partners.brand')),
                ('size', models.ManyToManyField(blank=True, null=True, to='products.Size')),
            ],
        ),
    ]
